### ISSUE TITLE
Prettify the UI

### ISSUE THREAD

**Issue by stevenguh** [stevenguh/face-off#14]
The following items are just the things that I see can be improved

- More graphics on the loading screen and less words
- The sections on the landing page doesn't look like sections
- Use a button with github icon to link back to github instead of a simple. Front awesome can probably help here. For example: the github button in https://lunar.fyi.
- Mention the Apple watch app on this page and link if it is on the Apple Store

**Comment by codycodes** [comment]
That button is pretty cool.
Linking to the Apple Watch app page is definitely needed and easy.
Some of the other things we can discuss to figure out what's a good solution. Let's regroup and talk about this issue when we get a chance!

**Comment by stevenguh** [comment]
Eventually, we should have a page for the apple watch app. As for now, I think we need to mentioned that a watch app is also in development since  we are sharing the name.

UI inspiration https://www.apple.com/covid19/
Btw, they are using react :)
